name: Mirror Clang

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  mirror-clang:
    runs-on: ubuntu-latest
    steps:
      - name: Set release tag
        id: set_tag
        run: |
          # Bisa kamu ubah logika penamaan tag sesuai kebutuhan
          echo "tag=clang-r563880b" >> $GITHUB_OUTPUT

      - name: Download Clang tarball
        run: |
          curl -L "https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/67af9f576276f27363074c4388e2cf0963bab6df/clang-r563880b.tar.gz" -o clang.tar.gz

      - name: Generate release notes
        id: notes
        run: |
          echo "Downloaded from: https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/67af9f576276f27363074c4388e2cf0963bab6df/clang-r563880b.tar.gz" > release-notes.txt
          echo "SHA256: $(sha256sum clang.tar.gz | cut -d' ' -f1)" >> release-notes.txt

      - name: Check if release exists
        id: check_release
        run: |
          TAG="${{ steps.set_tag.outputs.tag }}"
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/releases/tags/$TAG)
          echo "status=$STATUS" >> $GITHUB_OUTPUT

      - name: Create tag if missing
        if: steps.check_release.outputs.status != '200'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git tag ${{ steps.set_tag.outputs.tag }}
          git push origin ${{ steps.set_tag.outputs.tag }}

      - name: Create GitHub Release
        if: steps.check_release.outputs.status != '200'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.set_tag.outputs.tag }}
          name: ${{ steps.set_tag.outputs.tag }}
          body_path: release-notes.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.set_tag.outputs.tag }}
          files: clang.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
